version: "3.8"

services:
  jupyter:
    build: .
    restart: always
    ports:
      - "8891:8888"   # Host 8891 → Container 8888
    volumes:
      - ./notebooks:/usr/src/app/notebooks:rw
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "diego"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
